"""init

Revision ID: 138c3a3ddbfc
Revises: 
Create Date: 2026-01-12 17:49:25.615255

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '138c3a3ddbfc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accidents',
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('accidents_pkey'))
    )
    op.create_index(op.f('accidents_id_idx'), 'accidents', ['id'], unique=False)
    op.create_index('idx_accidents_location', 'accidents', ['location'], unique=False, postgresql_using='gist', if_not_exists=True,)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_accidents_location', table_name='accidents', postgresql_using='gist')
    op.drop_index(op.f('accidents_id_idx'), table_name='accidents')
    op.drop_table('accidents')
    # ### end Alembic commands ###
